name: go_router_poc
description: "A PoC project for using go_router"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0
  build_verify: ^3.1.0
  go_router_builder: ^2.4.0

flutter:
  uses-material-design: true
